app:
  env: dev
  http_port: "8081"

database:
  dsn: "${DATABASE_DSN}"
  db_timeout_seconds : 5

ethereum:
  chain_id: 11155111
  confirmation_depth: 12
  min_deposit_wei: "1"

scanner:
  name: native_eth_deposit_scanner
  start_block: 11008017
  batch_size: 10

explorer:
  base_url: "http://localhost:8080"
  timeout_seconds: 5

worker:
  interval_seconds: 5
  scanner_run_once_timeout_seconds: 60
  credit_run_once_timeout_seconds: 60